version: '3'

services:
    samba:
        image: ${LXNET_SAMBA_IMAGE}:${LXNET_SAMBA_VERSION}
        container_name: LXMon_LXNet_Samba
        hostname: LXMon_LXNet_Samba
        restart: ${RESTART_POLICY}
        ports:
            - ${LXNET_IP}:137:137/udp
            - ${LXNET_IP}:138:138/udp
            - ${LXNET_IP}:139:139/tcp
            - ${LXNET_IP}:445:445/tcp
        env_file:
            - ${LXMON_PATH}/Components/LXNetSamba/users.env
            - ${LXMON_PATH}/Components/LXNetSamba/shares.env
            - ${LXMON_PATH}/Components/LXNetSamba/config.env
        environment:
            - TZ:${TIMEZONE}
        volumes:
            - "${LXMON_PATH}/Shared Volumes:/shares"