version: '3'

services:
    onedrive:
        image: driveone/onedrive:latest
        restart: unless-stopped
        container_name: LXM_OneDrive
        environment:
            - TZ=Europe/London
        volumes:
            - ./Volumes/Config:/onedrive/conf
            - ./Volumes/LXShare:/onedrive/data