version: '3'

services:
    onedrive:
        image: driveone/onedrive:latest
        restart: unless-stopped
        container_name: LXM_OneDrive
        environment:
            - TZ=Europe/London
        volumes:
            - ./Volumes/Config:/onedrive/conf
            - ./Volumes/LXShare:/onedrive/data
    ntp:
        image: cturra/ntp:latest
        container_name: ntp
        restart: always
        ports:
            - 123:123/udp
        read_only: true
        tmpfs:
            - /etc/chrony:rw,mode=1750
            - /run/chrony:rw,mode=1750
            - /var/lib/chrony:rw,mode=1750
        environment:
            - NTP_SERVERS=time.cloudflare.com
            - LOG_LEVEL=0