#!/bin/bash

function line() {
 echo "----------------------------------------------------------------------------------------------------"
}

# get the load averages
read one five fifteen rest < /proc/loadavg

function uptime() {
    let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
    let secs=$((${upSeconds}%60))
    let mins=$((${upSeconds}/60%60))
    let hours=$((${upSeconds}/3600%24))
    let days=$((${upSeconds}/86400))
    printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"
}

line

date +"%A, %e %B %Y, %r"

echo ""

echo "[Uptime]            `uptime`"
echo "[Memory]            `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total) "
echo "[Running Processes] `ps ax | wc -l | tr -d " "`"
echo "[Load Average]      ${one}, ${five}, ${fifteen} (1, 5, 15 min)"